<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Bienvenido a Diksmarket</title>

<style type="text/css">
<!--
body {
	background-image: url(fondotitulo.jpg);
}
-->
</style></head>

<body bgcolor="#FFFFFF" text="#FFFFFF">
<h1 align="center" style="background-color:#33FFFF" > Bienvenido a Disk Market </h1>
</body>

</html>
